image: keymetrics/pm2:18-alpine
options:
  docker: true
  size: 2x
pipelines:
  branches:
    testing:
      - step:
          name: Build and Test & Pudh
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=frontend-whatsapp-bsp-${BITBUCKET_BRANCH}
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
            - docker load --input "${IMAGE_NAME}.tar"
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - IMAGE=${DOCKERHUB_USERNAME}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:latest"
            - docker push "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:latest"
          services:
            - docker
          size: 2x
          caches:
            - docker
            - node
          artifacts:
            - "*.tar"

definitions:
  services:
    docker:
      memory: 2048 
